steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}" \
          --region "${_DEPLOY_REGION}" \
          --platform managed \
          --allow-unauthenticated \
          --cpu 8 --memory 32Gi --no-cpu-throttling --concurrency 1 \
          --gpu 1 --gpu-type nvidia-l4 --no-gpu-zonal-redundancy \
          --max-instances 1 --min-instances 0 \
          --startup-probe="httpGet.path=/healthz,httpGet.port=8080,initialDelaySeconds=0,periodSeconds=10,failureThreshold=24,timeoutSeconds=5"

timeout: 1800s

images:
  - "${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPO}/${_SERVICE_NAME}:${COMMIT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY
